<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIUpTgkn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIUpTgkn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIUpTgkn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIUpTgkn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIUpTgkn\App_KernelDevDebugContainer([
    'container.build_hash' => 'IUpTgkn',
    'container.build_id' => '0e71104e',
    'container.build_time' => 1657525546,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIUpTgkn');
