<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container13rLKU5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container13rLKU5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container13rLKU5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container13rLKU5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container13rLKU5\App_KernelDevDebugContainer([
    'container.build_hash' => '13rLKU5',
    'container.build_id' => '2ca41e6f',
    'container.build_time' => 1656575249,
], __DIR__.\DIRECTORY_SEPARATOR.'Container13rLKU5');
