<?php

namespace ContainerIUpTgkn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VgBWRuZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VgBWRuZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VgBWRuZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordEncoder' => ['services', '.container.private.security.password_encoder', 'get_Container_Private_Security_PasswordEncoderService', true],
            'repo' => ['privates', 'App\\Repository\\RubriqueRepository', 'getRubriqueRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.VgBWRuZ.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.VgBWRuZ": it references class "App\\Entity\\User" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'passwordEncoder' => '?',
            'repo' => 'App\\Repository\\RubriqueRepository',
            'user' => 'App\\Entity\\User',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
