<?php

namespace ContainerIUpTgkn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ECSITVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eC_SITV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eC_SITV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\RubriqueRepository', 'getRubriqueRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.eC_SITV.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.eC_SITV": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'repo' => 'App\\Repository\\RubriqueRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
