<?php

namespace ContainerIUpTgkn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KSI1PkqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KSI1Pkq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KSI1Pkq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'repo' => ['privates', 'App\\Repository\\RubriqueRepository', 'getRubriqueRepositoryService', true],
        ], [
            'authenticationUtils' => '?',
            'repo' => 'App\\Repository\\RubriqueRepository',
        ]);
    }
}
