<?php

namespace ContainerIUpTgkn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GD1nm_PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gD1nm.p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gD1nm.p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordEncoder' => ['services', '.container.private.security.password_encoder', 'get_Container_Private_Security_PasswordEncoderService', true],
            'repo' => ['privates', 'App\\Repository\\RubriqueRepository', 'getRubriqueRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'passwordEncoder' => '?',
            'repo' => 'App\\Repository\\RubriqueRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
