<?php

namespace ContainerIUpTgkn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z2AXwfXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z2AXwfX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z2AXwfX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo3' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'repo4' => ['privates', 'App\\Repository\\RubriqueRepository', 'getRubriqueRepositoryService', true],
            'rub' => ['privates', '.errored..service_locator.Z2AXwfX.App\\Entity\\Rubrique', NULL, 'Cannot autowire service ".service_locator.Z2AXwfX": it references class "App\\Entity\\Rubrique" but no such service exists.'],
        ], [
            'repo3' => 'App\\Repository\\ProduitRepository',
            'repo4' => 'App\\Repository\\RubriqueRepository',
            'rub' => 'App\\Entity\\Rubrique',
        ]);
    }
}
