<?php

namespace ContainerIUpTgkn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRubriqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Z2AXwfX.App\Entity\Rubrique' shared service.
     *
     * @return \App\Entity\Rubrique
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Z2AXwfX": it references class "App\\Entity\\Rubrique" but no such service exists.');
    }
}
