<?php

namespace ContainerPAEm3zI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4vSeYdXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4vSeYdX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4vSeYdX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CartController::add' => ['privates', '.service_locator.KGarYJv', 'get_ServiceLocator_KGarYJvService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.6bilyEb', 'get_ServiceLocator_6bilyEbService', true],
            'App\\Controller\\CartController::remove' => ['privates', '.service_locator.KGarYJv', 'get_ServiceLocator_KGarYJvService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.C2jSuPc', 'get_ServiceLocator_C2jSuPcService', true],
            'App\\Controller\\HomeController::sousRubrique' => ['privates', '.service_locator.ttDQmmY', 'get_ServiceLocator_TtDQmmYService', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.bn70ThF', 'get_ServiceLocator_Bn70ThFService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.QXb2VJW', 'get_ServiceLocator_QXb2VJWService', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator.Nz8B.im', 'get_ServiceLocator_Nz8B_ImService', true],
            'App\\Controller\\ProduitController::produits' => ['privates', '.service_locator.Z2AXwfX', 'get_ServiceLocator_Z2AXwfXService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.FikVZzg', 'get_ServiceLocator_FikVZzgService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.MddjnQw', 'get_ServiceLocator_MddjnQwService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.KSI1Pkq', 'get_ServiceLocator_KSI1PkqService', true],
            'App\\Controller\\TestController::index' => ['privates', '.service_locator.KSI1Pkq', 'get_ServiceLocator_KSI1PkqService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.VgBWRuZ', 'get_ServiceLocator_VgBWRuZService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.NpdYCes', 'get_ServiceLocator_NpdYCesService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.gD1nm.p', 'get_ServiceLocator_GD1nm_PService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.eC_SITV', 'get_ServiceLocator_ECSITVService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CartController:add' => ['privates', '.service_locator.KGarYJv', 'get_ServiceLocator_KGarYJvService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.6bilyEb', 'get_ServiceLocator_6bilyEbService', true],
            'App\\Controller\\CartController:remove' => ['privates', '.service_locator.KGarYJv', 'get_ServiceLocator_KGarYJvService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.C2jSuPc', 'get_ServiceLocator_C2jSuPcService', true],
            'App\\Controller\\HomeController:sousRubrique' => ['privates', '.service_locator.ttDQmmY', 'get_ServiceLocator_TtDQmmYService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.bn70ThF', 'get_ServiceLocator_Bn70ThFService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.QXb2VJW', 'get_ServiceLocator_QXb2VJWService', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator.Nz8B.im', 'get_ServiceLocator_Nz8B_ImService', true],
            'App\\Controller\\ProduitController:produits' => ['privates', '.service_locator.Z2AXwfX', 'get_ServiceLocator_Z2AXwfXService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.FikVZzg', 'get_ServiceLocator_FikVZzgService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.MddjnQw', 'get_ServiceLocator_MddjnQwService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.KSI1Pkq', 'get_ServiceLocator_KSI1PkqService', true],
            'App\\Controller\\TestController:index' => ['privates', '.service_locator.KSI1Pkq', 'get_ServiceLocator_KSI1PkqService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.VgBWRuZ', 'get_ServiceLocator_VgBWRuZService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.NpdYCes', 'get_ServiceLocator_NpdYCesService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.gD1nm.p', 'get_ServiceLocator_GD1nm_PService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.eC_SITV', 'get_ServiceLocator_ECSITVService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CartController::add' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CartController::remove' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::sousRubrique' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Controller\\ProduitController::produits' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TestController::index' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CartController:add' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CartController:remove' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:sousRubrique' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'App\\Controller\\ProduitController:produits' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TestController:index' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
